CREATE TABLE IF NOT EXISTS notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_id BIGINT NOT NULL REFERENCES states(id),
    created_by BIGINT NOT NULL REFERENCES users(id),
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    image TEXT NOT NULL,
    importance VARCHAR(16) NOT NULL,
    published_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at VARCHAR(255),
    deleted_by VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT notices_importance_check CHECK (importance IN ('baja', 'media', 'alta'))
);

CREATE INDEX IF NOT EXISTS notices_feed_idx
    ON notices (state_id, importance, published_at DESC);

CREATE TABLE IF NOT EXISTS member_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_key VARCHAR(32) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    file_path TEXT,
    original_filename VARCHAR(255),
    cover_path TEXT,
    overlay_color VARCHAR(16) NOT NULL DEFAULT '#0f172a',
    overlay_opacity INTEGER NOT NULL DEFAULT 68,
    updated_by BIGINT REFERENCES users(id),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

INSERT INTO member_documents (document_key, title, created_at, updated_at)
VALUES
    ('member_guide', 'Manual de miembros', NOW(), NOW()),
    ('statutes', 'Estatutos', NOW(), NOW()),
    ('safety_talks', 'Charlas de seguridad', NOW(), NOW()),
    ('brand_manual', 'Manual de marca', NOW(), NOW()),
    ('board_resolutions', 'Resoluciones del directorio', NOW(), NOW())
ON CONFLICT (document_key) DO NOTHING;
